version: "3.3"
services:
  agrorob_server:
    ports: 
    - 7447:7447
    - 8000:8000
    build: .
    network_mode: "host"
    environment:
      - ZENOH_URL=tcp/<ENTER_ZENOH_IP>:<ENTER_ZENOH_TCP_PORT>
