version: "3.3"
services:
  zenoh:
    container_name: zenoh_router
    image: eclipse/zenoh
    restart: always
    ports:
      - 8447:7447 # port re-map
      - 8000:8000
    volumes:
      - ./data:/root/.zenoh
      - ./router_with_tls.json5:/etc/zenoh/router.json5
      - ./entrypoint.sh:/entrypoint.sh:ro
      - /etc/cert/:/etc/zenoh/cert # cert and key location
    environment:
      - RUST_LOG=debug
    entrypoint: /entrypoint.sh # Specify entrypoint file
