version: "3.3"
services:
  agrorob_emulator:
    build: .
    # ports:
    #   - "5000:5000"
    network_mode: "host"
  zenoh-bridge-dds:
    image: "eclipse/zenoh-bridge-dds:main"
    build: 
      args:
        - m = peer
        - e = tcp/57.129.16.234:8447
    ports: 
        - 7447:7447
        - 8000:8000

    network_mode: "host"
    
    entrypoint: /entrypoint.sh 
