version: "3.3"
services:
  agrorob_emulator:
    build: .
    network_mode: "host"
    volumes:
      - ./r_entrypoint.sh:/r_entrypoint.sh:ro
    entrypoint: /r_entrypoint.sh 
  zenoh-bridge-dds:
    image: "eclipse/zenoh-bridge-dds:main"
    ports: 
        - 7447:7447
        - 8000:8000
    volumes:
      - ./data:/root/.zenoh-bridge-dds
      - ./entrypoint.sh:/entrypoint.sh:ro
    network_mode: "host"
    env_file:
      - ./environment.env
    entrypoint: /entrypoint.sh 
